name: Bug Report
description: "Create a report to help us improve."
body:
  - type: textarea
    id: problem
    attributes:
      label: Description of the problem
      placeholder: Your problem description
    validations:
      required: true

  - type: input
    id: go-env
    attributes:
      label: Used Go version
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: Code example or link to a code snippet
      value: |-
        <details>

        ```go
        // add used code here
        ```

        </details>
    validations:
      required: true